GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO PUBLIC;


GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO PUBLIC;


GO
GRANT CONNECT TO [TYLER\amanda.houseman];


GO
GRANT EXECUTE
    ON SCHEMA::[dbo] TO [TYLER\amanda.houseman];

